DROP TABLE IF EXISTS quiz_answers CASCADE;

CREATE TABLE quiz_answers (
 id SERIAL PRIMARY KEY NOT NULL,
 question_id INTEGER REFERENCES quiz_questions(id) ON DELETE CASCADE,
 answer TEXT NOT NULL,
 is_correct BOOLEAN DEFAULT FALSE
);
